### ISSUE TITLE
Make more explicit that WorkChain defintion needs to be in separate file

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-tutorials#110]
I think this should be mentioned in the tutorial, but maybe not clear enough. Any WorkChain defintion needs to be in a separate file from the script launching it. Otherwise you get `ImportError` `__main__.EquationOfState` not found

**Comment by ltalirz** [comment]
can we remove this requirement in aiida-core?

**Comment by sphuber** [comment]
I am not sure this is possible since this is just a python thing. The engine needs to be able to load the class, but if it is defined in the same script as the launch script, the module path will be `__main__:EquationOfState`. Since the engine cannot possible know where to find `__main__` it just cannot load the class.

I am about to open another related issue which makes the situation worse when submitting
