### ISSUE TITLE
encounter duplicate entry points issue (xiamen-2019)

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-tutorials#127]
The same issue as https://github.com/aiidateam/aiida-quantumespresso/issues/267 happening.
Have to run `reentry scan` to get rid of it.

**Comment by ltalirz** [comment]
Indeed... also this we will fix in the next VM build.
The underlying reentry issue I still have to investigate.

**Comment by ltalirz** [comment]
should be fixed in build 3 of the VM (note to self:  remember to `reentry scan` whenever updating plugins)
