### ISSUE TITLE
Report of tutorial tests in the remote VMs

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-tutorials#128]
I tested sections 1 through 4 of [AiiDA's latest tutorial](https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_MARVEL_Psik_MaX/index.html); almost all seems to be working correctly but I had the following problems/comments:

(1) I would maybe emphasize that the config file in .ssh needs to be adjusted in order to properly access the notebook from the local computer. Maybe it's just me that I'm sloppy, but since I was able to connect just with the .pem file (is that a key?) you sent me, I thought I didn't need the config and so had problems with this.

(2) This might be silly, but why is section 2.5 empty?

(3) Am I doing something wrong or there is no QE code in the VMs? At least not in the folder of the .yml config file that is in the tutorial. I found one at `/usr/local/bin/pw.x` and could modify the .yml to point to it and use it without any problems, is this the code they are supposed to be using?

**Comment by ltalirz** [comment]
@ramirezfranciscof Thanks a lot for your help and feedback!

Re 1: Ok, I'll think about how to better highlight this.

Re 2: Hehe, good point. I guess it should be removed (it was probably moved/split up)

Re 3: Indeed, the location of pw.x has moved and we will need to adjust this in the tutorial.

**Comment by ltalirz** [comment]
all changes will be made in the xiamen2019 branch

**Comment by ltalirz** [comment]
fixed.
