### ISSUE TITLE
local jupyter notebook servers break tunneling setup

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#146]
several people ran into issues because they were running jupyter notebook servers locally already, causing the jupyter notebook server started on the VM to write something like
 `https://(workhorse or 127.0.0.1):8888/.../...`

Perhaps (to test), one solution could be to forward a range of ports starting at 8888

Of course, this is only an issue when using ssh tunneling - not when connecting directly to the port 8888 of the VM via a browser (which did not work on huawei cloud, however).

**Comment by giovannipizzi** [comment]
For now I'm going to fix this by putting a note at the beginning of the setup section.
Would this be ok for you to close it?
Is it ok to just fix it in the most recent tutorial (Ljubljana in this case) to close this issue? We have to remember to copy from the correct earlier version when preparing future tutorials

**Comment by ltalirz** [comment]
> For now I'm going to fix this by putting a note at the beginning of the setup section. Would this be ok for you to close it?

Yes.

> Is it ok to just fix it in the most recent tutorial (Ljubljana in this case) to close this issue? We have to remember to copy from the correct earlier version when preparing future tutorials

Yes - up to you. Usually, I've corrected errors in the old materials as well, while for issues that add new material I've not "backported" them.
This case is perhaps a bit in a gray area.

**Comment by ltalirz** [comment]
It seems this was overlooked when preparing the 2020 tutorial.
I will put this back in via the "Troubleshooting" section
