### ISSUE TITLE
participants were using xshell instead of putty

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#147]
almost all windows users at the tutorial were using [xshell](https://www.netsarang.com/en/xshell/) instead of putty.
we might want to update the "Getting started" instructions accordingly

**Comment by giovannipizzi** [comment]
It's a commercial software, with a 30-days evaluation... do we really want to suggest this? I would be tempted to close this issue as a `wontfix`

**Comment by ltalirz** [comment]
I see... It's free for non-commercial use https://www.netsarang.com/en/free-for-home-school/
Still, perhaps let's reevaluate this after the slovenia tutorial.
