### ISSUE TITLE
🧪 TEST: Make sure all calculations run finish in reasonable time

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-tutorials#151]
During the Ljubljana tutorial, we realised that running in a VM with 3 vCPUs was *way* slower than running in a machine with 2 vCPUs (something like after 1 hour still only ~50 kpoints for the bands were run, while with 2 vCPUs it finished the whole bands workflow in ~10 minutes).

This happened both on my Mac and on the laptop of one of the participants, so it seems to be reproducible.

I guess (but I'm not sure?) that it might be to the way the parallelisation works in QE, and/or to how the vCPUs are assigned by VirtualBox, but maybe (?) also due to disk I/O or memory and swaps.

I think in the initial note of the tutorial we should say to increase the number of CPUs to two, but not to use 3 CPUs (but possibly powers of two might also work very well).

Mentioning @sphuber @ltalirz @yakutovicha @CasperWA so they  know for future tutorials as well (and maybe we should check if this happens also in the Quantum Mobile and mention this there as well, in the troubleshooting?)

**Comment by ltalirz** [comment]
very strange... so just to understand:
 * this is on a custom Virtualbox VM
 * you are using the `direct` scheduler (not slurm)

correct?
Can you put a link to the part of the tutorial you ran so that we can try reproducing it later?

**Comment by giovannipizzi** [comment]
> this is on a custom Virtualbox VM

Yes

> you are using the direct scheduler (not slurm)

Yes. Also, I don't specify the number of CPUs so it uses all those available.

It's the demo_bands, in the last section.

**Comment by ltalirz** [comment]
I thought this as well at first but Giovanni is talking about a VM that runs on your laptop with virtualbox

**Comment by mbercx** [comment]
I'll add this as a "final check" to the current tutorial project, since we should have an idea of how long the calculations take on the AiiDAlab JupyterHub k8s setup, and adjust (material or cluster) if required.

**Comment by mbercx** [comment]
AFAIK, we didn't have any calculations in the tutorial that took a problematic amount of time.
