### ISSUE TITLE
add an example with "verdi process status" in first taste

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#163]
For the last section of "first taste" where running the workchain:
"verdi process status" provides a nice overview of the hierarchy how things are called.

**Comment by chrisjsewell** [comment]
Hmm, searching in the 2020 Intro tutorial, `verdi process status` only shows up in the base restart work chain section. Agree it is a nice command, so will leave this open for next time! (and @mbercx maybe mention it tomorrow morning)

**Comment by mbercx** [comment]
Along the same lines: often the participants will have forgotten about the PK of the structure they are using (at least I do). Maybe we can show them `!verdi data structure list` for following tutorials?

**Comment by mbercx** [comment]
The `verdi process status` command is now mentioned in the basic tutorial (see [this PR](https://github.com/aiidateam/aiida-core/pull/4508)), which will serve as the starting point for future tutorials.
