### ISSUE TITLE
provenance browser issues

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#164]
We do write that the "use your own restapi" is tested only with firefox and safari, but it's not very visible.
It would be great if we could display a warning message, when someone is using the provenance browser a non-supported browser (which seems to apply to internet explorer, edge, vivaldi, safari, ...)

**Comment by mbercx** [comment]
@ltalirz do you think this is still an issue? We will probably use `ngrok` to have the participants use the REST API.

**Comment by ltalirz** [comment]
well, it's still mentioned on https://www.materialscloud.org/explore/connect

in any case, this would seem more like an issue for the AiiDA explorer app

**Comment by ltalirz** [comment]
replaced by https://github.com/materialscloud-org/aiida-explorer/issues/38
