### ISSUE TITLE
add example of .store() method

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#167]
paraphrasing suggestion by @atztogo :  

one of the biggest hurdles for me to understand was what the `Int`, `Str`, `Dict`, `SinglefileData` classes do, and what happens when you `.store()` them.
It would be nice if this was explained in the tutorial using a simple example.

**Comment by sphuber** [comment]
We should, I think, stress, if adding such a section, that this is really only necessary if you are creating new `Data` nodes by hand. If you are creating inputs for a calculation there is no need to store them, nor when creating outputs that are returned from calcfunctions and calculation jobs.

**Comment by mbercx** [comment]
Since we now show this in the `AiiDA Basics` module in the context of an `Int` node. The section also clearly shows that when running e.g. a `calcfunction`, the input and output nodes are automatically stored.
