### ISSUE TITLE
consider adding a "launch on binder"  button

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#17]
see [here](https://nbsphinx.readthedocs.io/en/0.4.2/never-execute.html) for an example of how to do this *inside* the sphinx documentation
https://github.com/spatialaudio/nbsphinx/tree/0.4.2/binder

**Comment by mbercx** [comment]
@ltalirz as we currently offer the option of running the tutorial content on the AiiDAlab demo server, can this issue be closed?

**Comment by ltalirz** [comment]
yes, let's close
