### ISSUE TITLE
Unable to find the "PwBandStructureWorkChain" in provenance browser

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#176]
The Mandi tutorial instructs to:

> Use the provenance browser to explore the steps of the PwBandStructureWorkChain

I was not able to find that in the browser.

**Comment by chrisjsewell** [comment]
This line isn't in the 2020 Into tutorial (we introduce the `PwBandStructureWorkChain` later on in the tutorial)
