### ISSUE TITLE
The node with UUID "ce81c420-7751-48f6-af8e-eb7c6a30cec3" is not available

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#177]
The Mandi tutorial instructs to copy & paste the "ce81c420-7751-48f6-af8e-eb7c6a30cec3" UUID, however that node does not appear to exist.

>  If you ever get lost, just go to the “Details” tab, enter ce81c420-7751-48f6-af8e-eb7c6a30cec3 and click on the “GO” button.

Doing this I get an empty result page with an error message that briefly flashes in the header and then disappears:

> Error while getting data from the server (either server is down or passed node uuid is not available)!

**Comment by csadorf** [comment]
Issue occurred, because I did not *restart* the restapi endpoint after importing data into the "quickprofile" profile instead of "generic". It might be helpful to add a fat warning about that.

**Comment by mbercx** [comment]
I don't think this material exists anymore, so I'm going to close this issue. Feel free to reopen in case I'm mistaken!
