### ISSUE TITLE
The `verdi calcjob` `--color` option does not enable distinction between files and folders

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#178]
The Mandi tutorial states

> Adding a `--color` flag allows you to easily distinguish files from folders by a different coloring.

However, using that flag *all* entries are simply presented in blue and it seems that files and folders are **actually distinguished by the font weight** with directories shown in bold.

**Comment by sphuber** [comment]
This will be fixed in `aiida-core==1.3.0`. That is to say `--color` will now only cause folders to be coloured

**Comment by chrisjsewell** [comment]
thanks @sphuber, I'll close this then
