### ISSUE TITLE
🧪 TEST: Make sure the utf-8 symbol for "waiting" is displayed correctly

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#183]
See screenshot:
![Screenshot from 2019-10-04 18-12-42](https://user-images.githubusercontent.com/1441208/66222965-a3f87300-e6d2-11e9-825b-52b8c58f1cfd.png)

**Comment by csadorf** [comment]
Should this be mentioned in the tutorial or the AiiDA documentation?

**Comment by sphuber** [comment]
We should first figure out if that fixes the problem on the VM. If so, we can add it to the `.bashrc` of the image, but for this to take effect on the tutorial itself a new VM would have to be built. As I asked in another issue, I am not sure if @CasperWA and @yakutovicha want to do this

**Comment by csadorf** [comment]
I added the following lines to my `~/.bashrc` file on the VM:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
and then started a new sessions and it did **not** fix the issue.

**Comment by mbercx** [comment]
Will add this to the project so we can check it, but I think it's fine for the AiiDAlab cluster and QM.

**Comment by mbercx** [comment]
Just checked, and this no longer seems to be an issue on an AiiDAlab install:

![Screenshot 2022-01-31 at 12 58 52](https://user-images.githubusercontent.com/25607960/151790457-2b4dbeb5-db51-4ab4-8453-939bf93ae943.png)
