### ISSUE TITLE
Encounternig warning trying to import "aiida_tutorial_2019_05_perovskites_v0.3.aiida"

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#184]
Trying to execute the `verdi import https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms/tutorials/aiida_tutorial_2019_05_perovskites_v0.3.aiida`, I get the following warning:

> Warning: Export file version is 0.4, can import only version 0.7

Does this need to be addressed?

**Comment by sphuber** [comment]
We decided to keep this, because all the user has to do is press enter for the archive to be automatically migrated before being imported. But @CasperWA and @yakutovicha  if you prefer it fixed we will have to migrate the archives ourselves and upload the new version, while updating the permanent link in the tutorial text

**Comment by csadorf** [comment]
Alternatively the warning could be addressed in the tutorial or we don't do anything. I just reported this, because this warning and the additionally required user action represent a slight mismatch between what is presented in the tutorial and the UX.

**Comment by ltalirz** [comment]
This issue persists and it would be nice to upload the migrated file.

**Comment by sphuber** [comment]
I have migrated the file. Who can upload this to the Materials Cloud?
File is here: https://drive.google.com/file/d/1FWuOrgsuBDtDt6FLXegB4IEdNGUwYZR0/view?usp=sharing
Archive now has v0.9 which is compatible with `aiida-core==1.3.0`

**Comment by ltalirz** [comment]
Thanks, will do!

**Comment by csadorf** [comment]
@ltalirz Is this issue resolved with the merge of #236 ?

**Comment by ltalirz** [comment]
yes. I guess it would be closed automatically when the intro branch is merged in to develop.
