### ISSUE TITLE
Launching `verdi shell` emits deprecation warning

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#187]
Executing the `verdi shell` command, the user is presented with the following warning:

```
/home/max/codes/aiida-core/aiida/backends/profile.py:23: AiidaDeprecationWarning: this module is deprecated
  warnings.warn('this module is deprecated', AiidaDeprecationWarning)  # pylint: disable=no-member
```

**Comment by ltalirz** [comment]
this would be fixed by switching to the latest `develop` branch of aiida-core

**Comment by csadorf** [comment]
> this would be fixed by switching to the latest `develop` branch of aiida-core

@ltalirz Are you suggesting this as a potential solution/work-around or is this just a note for future reference? Because I created this issue specifically in the context of testing the Mandi tutorial under *production* conditions on the VM provided to tutorial participants, so switching the software to a different branch is not an acceptable solution or work-around.

**Comment by ltalirz** [comment]
This was more for future reference - since there is no real impact on usability from this issue, I guess it's not really pressing to fix for the tutorial

**Comment by csadorf** [comment]
Got it. I agree that this is probably not urgent.

**Comment by sphuber** [comment]
On this note though will the VM used for the tutorial use `aiida-core==1.0.0b6`? Because there are quite a few nasty bugs that have been solved since then in `develop`. Notably #191 gave quite some problems, which is now fixed. Does it make sense to update the VM to a more recent commit?

**Comment by CasperWA** [comment]
> On this note though will the VM used for the tutorial use `aiida-core==1.0.0b6`? Because there are quite a few nasty bugs that have been solved since then in `develop`. Notably #191 gave quite some problems, which is now fixed. Does it make sense to update the VM to a more recent commit?

Ah, here is the comment on creating a new VM.
I am not sure we will have the time to create a new VM, but we may have time to manually update each machine (or even have them do it initially before starting).
What do you think @yakutovicha?

**Comment by csadorf** [comment]
While I was not asked, I would definitely advise against updating manually for this particular issue.

**Comment by CasperWA** [comment]
> While I was not asked, I would definitely advise against updating manually for this particular issue.

It was more for the bug mentioned by @sphuber as well, no worries. But also various other bugs that have been fixed since the release of beta 6.

**Comment by sphuber** [comment]
When does the tutorial start? Have the machines already been launched?

**Comment by ltalirz** [comment]
`verdi shell` no longer raises a deprecation warning in aiida 1.3.0
