### ISSUE TITLE
Description of command formatting in "verdi shell" section inaccurate

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#188]
The tutorial states that

> [verdi commands] will be marked in this document by a green background [...]

and 

> command-line instructions in bash to be typed into a terminal will be written with a blue background:

However, that is not the case with the current layout.

**Comment by CasperWA** [comment]
This looks fine to me in both the Edge and Chrome browser on Windows.
I will add a note stating different browsers may display the background colors differently.
