### ISSUE TITLE
Section 5: The tutorial flow is unclear

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-tutorials#192]
Section 5 contains various snippets and instructions of commands to be executed, however it is not always 100% clear what snippets are expected to be executed in a REPL, which are to be copied into a script, and which ones are purely illustrative. This makes it more difficult to follow and specifically leads to confusion when comparing against expected behavior. For example, in section 5.2 it is stated that

> For instance, you can check that the output links of initial_structure are the five rescale calculations:
> 
> ```
> initial_structure.get_outgoing().all_nodes()
> ```
> which outputs
> ```
> [<CalcFunctionNode: uuid: 9bc5e0f5-fbe4-4fad-a0d1-cf5893dac132 (pk: 437) (abc.rescale)>,
>  <CalcFunctionNode: uuid: 338858ce-779b-455a-8fad-6ac71ba0d1e3 (pk: 434) (abc.rescale)>,
>  <CalcFunctionNode: uuid: 0c601f8c-aa49-4957-bea1-cd796de4a323 (pk: 431) (abc.rescale)>,
>  <CalcFunctionNode: uuid: bbe4fab4-6939-4f05-8bcd-5120e03ddade (pk: 428) (abc.rescale)>,
>  <CalcFunctionNode: uuid: d5e68e04-8ab7-4f3a-90ff-a61f7fd4c247 (pk: 425) (abc.rescale)>]
> ```

However, that would only be true if the code was executed in a REPL, otherwise one would need to run it for example like this to obtain above shown output:
```
from pprint import pprint
pprint(initial_structure.get_outgoing().all_nodes())
```

In section 5.2.1, the user is instructed to
> Type in your shell (or modify the functions defined in `create_rescale.py` and then run):
However, this is the first time that the script file `create_rescale.py` is mentioned.

The tutorial then proceeds to provide instructions which appear to assume that the user is executing code in a REPL.

However, then again later, it is stated
> For your convenience, besides the functions that you have written so far in the file create_rescale.py

which is now very confusing, because again, the tutorial made it look like executing in the REPL was expected, and executing code in the script was completely optional.

I suggest to
1. Be way more explicit about how the user is expected to follow the tutorial.
2. Stick to either a REPL or a scripting approach, or at least, switch only *once*.
3. Distinguish much more clearly between snippets that are supposed to be executed and potentially copy & pasted by the user and those that are purely illustrative.

In addition, the code snippets are not consistently marked up with the appropriate prefixes, some snippets have REPL formatting (`In [x]` `Out[x]`, etc), others don't, but not even consistently with expected behavior (see example quote above).

**Comment by chrisjsewell** [comment]
In 2020 intro tutorial, where this has been rewritten, I believe this to be fixed,
and certainly there was no confusion from the participants over how to run the code
