### ISSUE TITLE
meaning of PK not intuitive

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#201]
Feedback from @atztogo 

> I got a comment from a participant that to understand what PK in 'A first taste' means was difficult.
> The tutorial documentation tells enough, but if I understand correctly their feeling, the concept of 'data' in AiiDA is at first not very clear for them. For example, cif file is data, and it's identifier is the set of attributes such as name, 'crystal structure', etc. People are familiar with this way. But why can it be a number? I can't tell it in a nice way, but this was a good comment to remind me to think.

**Comment by mbercx** [comment]
This is in part also a problem because when you do e.g.:

```console
$ verdi data structure list
  Id  Label    Formula
----  -------  ---------
  87           Si2
 120           Si2
 134           Si2
```

The table show `Id` (which we should really fix), whereas:

```console
$ verdi process list -a
  PK  Created    Process label                 Process State    Process status
----  ---------  ----------------------------  ---------------  ------------------------------------------------------------------------------------
 105  22D ago    PwBandsWorkChain              ⏹ Finished [0]
```

Will see if there is an issue open on `aiida-core` for this. For now, I'll close this issue, since the basics module explains this to quite some extent.
