### ISSUE TITLE
Unifying "general" tutorial

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-tutorials#203]
From discussion with @sponce24 it seems difficult to find the "right" tutorial to start learning about AiiDA.
We could have a reference tutorial, directing to the "latest" tutorial named "the AiiDA tutorial", where one learns to setup a code, a computer, and more.

One may have something similar to `quicksetup` as well, but for going through with questions like "which code do you want to use?" "Put in path to the code" "What computer/cluster do you want to use?" "Provide me with the ssh key", ...

**Comment by CasperWA** [comment]
More goal-oriented tutorials, e.g., "I want a band structure", "I want an STM image", ...

**Comment by ltalirz** [comment]
sure, @csadorf is working on this

**Comment by CasperWA** [comment]
Thinking to something similar like the [abinit tutorial](https://docs.abinit.org/tutorial/).

**Comment by CasperWA** [comment]
Put current top-level tutorials under one branch "Schools", so that it is clear what is the tutorial versus where it has been used.

**Comment by chrisjsewell** [comment]
Is this all mainly addressed in the actual (revamped) documentation now?
On www.aiida.net, maybe it is a bit confusing now to have the `Tutorials` header link to the pages here, when really the "canonical source of truth" for getting started should be: https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/tutorial.html

These tutorials should really only be used by the actual participants of the specific tutorial, and maybe the most recent one as a source for additional learning

**Comment by ltalirz** [comment]
> Is this all mainly addressed in the actual (revamped) documentation now?

Yes, I think so. Closing.

> On www.aiida.net, maybe it is a bit confusing now to have the Tutorials header link to the pages here, when really the "canonical source of truth" for getting started should be: https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/tutorial.html
> These tutorials should really only be used by the actual participants of the specific tutorial, and maybe the most recent one as a source for additional learning

I agree. The tutorials are anyhow linked from the "Events" page (as well as from the docs at the appropriate place, I believe).
I've removed the "Tutorials" link from the menu on aiida.net

**Comment by chrisjsewell** [comment]
Thanks @ltalirz
