### ISSUE TITLE
Triage old issues, close those that don't apply, or fix those that do still apply

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-tutorials#212]
To be done before the 2020 tutorial

**Comment by ramirezfranciscof** [comment]
I've already reviewed the [issues without project](https://github.com/aiidateam/aiida-tutorials/issues?q=is%3Aissue+is%3Aopen+no%3Aproject) and added the ones that I thought were relevant to the 2021 tutorial project. I also went through the [notes from last virtual tutorial](https://docs.google.com/document/d/1PgrVEKP7OI75Vw-Vtzf2IF4ljHqoBQ203xYVKu-yAUw/edit#) and did the same.

I will ask at the AiiDA meeting for people to take a look too and then consider this task done.

**Comment by mbercx** [comment]
I'm working on it! 😁 

![image](https://user-images.githubusercontent.com/25607960/121337132-80acaf00-c91c-11eb-9949-e72a2c535870.png)

**Comment by mbercx** [comment]
Done!
