### ISSUE TITLE
Upgrade the export file to the most recent export format (0.9)

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-tutorials#213]
It's not critical, because migration will be performed automatically, but probably better to provide a recent-format?

**Comment by CasperWA** [comment]
Where is this file located? I can't seem to find it in this repo. I would have guessed under `assets`?

**Comment by CasperWA** [comment]
Never mind, it seems (from the filename) that this issue has already been fixed.
See tutorial link [here](https://github.com/aiidateam/aiida-tutorials/blame/2020-intro-week/docs/pages/2020_Intro_Week/sections/basics.rst#L674).

Please confirm that this is the only link to an export archive in the tutorial and close.

Tagging @giovannipizzi @chrisjsewell @mbercx

**Comment by chrisjsewell** [comment]
confirmed, we only link to the archive located at: https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms/tutorials/aiida_tutorial_2020_07_perovskites_v0.9.aiida
