### ISSUE TITLE
missing package when starting jupyter notebook server

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#237]
On the VM, I get the following when starting a jupyter notebook server:

```
$ jupyter notebook
[W 22:50:42.820 NotebookApp] Error loading server extension appmode.server_extension
    Traceback (most recent call last):
      File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/notebook/notebookapp.py", line 1572, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'appmode'
```
It seems `appmode` is missing in the relevant python environment(?)

**Comment by chrisjsewell** [comment]
Err I imagine thats meant to be bought in from aiidalab. I see at some point we forked it, but then archived the fork: https://github.com/aiidalab/aiidalab-appmode, @yakutovicha any thoughts?

**Comment by ltalirz** [comment]
@yakutovicha I realize that appmode is missing from the requirements installed by the latest aiidalab metapackage:
https://github.com/aiidalab/aiidalab/blob/develop/requirements.txt

Is this on purpose? How could this happen?

**Comment by ltalirz** [comment]
Perhaps the reason is that appmode is needed only in the environment running the jupyter notebook server?

@borellim In that case, we should add it explicitly here: https://github.com/marvel-nccr/ansible-role-aiidalab/blob/600efcd063d9c805cdc7598f580ba401c238cd25/tasks/prerequisites.yml#L34
(on the Quantum Mobile we are installing jupyter in the same environment as AiiDA)

**Comment by chrisjsewell** [comment]
Note that I haven't actually encountered this error in any of my testing, with newest VM build. @mbercx also look out for this

**Comment by mbercx** [comment]
I have also not encountered any issues running Jupyter notebooks, but I'll be sure to test it again when you set up the final VM.

**Comment by ltalirz** [comment]
The error turned up simply when running `jupyter notebook`
The notebook server itself still worked fine - but only without appmode, of course (i.e. no aiida lab)

**Comment by chrisjsewell** [comment]
oh yes I do see it now, @ltalirz any reason you can think of to not set it to the latest version: appmode==0.8.0?

**Comment by ltalirz** [comment]
The latest appmode should work perfectly fine - as mentioned, just add it to the aiidalab role
https://github.com/marvel-nccr/ansible-role-aiidalab/blob/600efcd063d9c805cdc7598f580ba401c238cd25/tasks/prerequisites.yml#L34

**Comment by yakutovicha** [comment]
> @yakutovicha I realize that appmode is missing from the requirements installed by the latest aiidalab metapackage:
> https://github.com/aiidalab/aiidalab/blob/develop/requirements.txt
> 
> Is this on purpose? How could this happen?

Yep, it was done on purpose, since appmode is installed in the "root" python environment.

**Comment by ltalirz** [comment]
This was fixed by @chrisjsewell in the VM for the tutorial (thanks again!)
