### ISSUE TITLE
basics: verdi process list output unexpected?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#238]
The output of `verdi process list -S finished` is not as described [here](https://aiida-tutorials.readthedocs.io/en/2020-intro-week/pages/2020_Intro_Week/sections/basics.html#processes).

In particular, there are 171 results, not 6.

Furthermore, the result of `verdi process list -S finished` and `verdi process list -a` is identical (all processes have "Finished" as the process state)

**Comment by sphuber** [comment]
Well it *does* say `looks something like`. We can't really show *all* results in the example output. And the fact that they are all finished, is just that is what the imported data happens to contain. We don't have any other states.

**Comment by mbercx** [comment]
During my reworking of the basics section (PR #245), I've added ellipses `...` and changed the `Total results` number to indicate that there are more results.

**Comment by ltalirz** [comment]
> And the fact that they are all finished, is just that is what the imported data happens to contain. We don't have any other states.

Sure. I guess we all agree though that demonstrating the effect of a filter function using an example where it has no effect on the output is not ideal ;-)
I guess this comes from the fact that this is old data and there used to be different statuses, but now there no longer are due to changes to process states.

Let's keep this issue open to remind ourselves that we should include processes with different statuses in the export file.

> During my reworking of the basics section (PR #245), I've added ellipses ... and changed the Total results number to indicate that there are more results.

Thanks!

**Comment by ramirezfranciscof** [comment]
I understand this should have been closed already? Feel free to re-open if I'm mistaken.
