### ISSUE TITLE
basics: section on codes unclear

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#240]
The [section on codes and computers](https://aiida-tutorials.readthedocs.io/en/2020-intro-week/pages/2020_Intro_Week/sections/basics.html#codes-and-computers) asks the user to list the codes available, but there are none (note that the "First taste" section was left out!).

The text clearly seems to expect a result (e.g. `Now, among the entries of the output you should also find the code just shown.`).
Given that the users only start setting up their own computers and codes in the following section 3, I wonder whether this subsection 2.1.5.3 can be deleted entirely?

**Comment by chrisjsewell** [comment]
> to list the codes available, but there are none

I'm not sure what you meant here; won't they already have codes to search for from the imported archive, i.e. in the processes section above it I can see that `verdi code show 825` should work?

> Now, among the entries of the output you should also find the code just shown

then this relates to that code

**Comment by ltalirz** [comment]
> I'm not sure what you meant here; won't they already have codes to search for from the imported archive

Yes, but they won't show up in `verdi code list` because they are created by a different user

**Comment by chrisjsewell** [comment]
but they will if using `-A`, as mentioned:

![image](https://user-images.githubusercontent.com/2997570/86182627-3de93100-bb28-11ea-8edb-2fb3340dfb42.png)

that was my interpretation of the Now, as in you won't see it with `verdi code list` but *Now* you will see it with `verdi code -a -A list`

(personally, as with groups, I don't think we should hide nodes with other users attached by default. It just makes it confusing when you import an archive, then they don't show up)

**Comment by ltalirz** [comment]
hi @chrisjsewell , as mentioned in the issue description, the sentence `Now, among the entries of the output you should also find the code just shown.` seems to refer to "the code" that was shown as the output of `verdi code list`.

In any case, we should warn users if we tell them "To show a list of all available codes type `verdi code list`" and then the output is empty.

I repeat my question: is this section 2.1.5.3 useful here at all?
`verdi computer list`  and `verdi code list` are both covered in section 3.

I think we should be looking for content to cut in section 2, and this is a clear candidate.

**Comment by chrisjsewell** [comment]
> I think we should be looking for content to cut in section 2, and this is a clear candidate.

ok yeh sounds reasonable. When we make this change, we should then maybe mention about `verdi code list -a -A` in section 3

**Comment by ltalirz** [comment]
This was fixed either in #236 or #245
