### ISSUE TITLE
👌 QE - Expose REST API and improve explanation

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-tutorials#279]
At the end of the second part of the tutorial we have the participants explore the provenance with the REST API. This works fine from the AWS machines (provided the 5000 port is forwarded), but we'll have to make sure that the REST API is exposed from the AiiDAlab cluster as well.

@giovannipizzi suggested using [ngrok](https://ngrok.com/), and @ltalirz was kind enough to provide a [notebook](https://github.com/aiidalab/aiidalab-aiida-cockpit/blob/cbf56ca8757639d5b5538f19bf3d90600320ec99/rest.ipynb) with more details on how to do this. (Also see [this PR](https://github.com/aiidalab/aiidalab-aiida-cockpit/pull/8))

Finally, @ramirezfranciscof [noted that](https://github.com/aiidateam/aiida-tutorials/pull/278#discussion_r531180642) the REST API part could use a little more guidance in his review of #278.

**Comment by mbercx** [comment]
Tested this together with @csadorf, and using `ngrok` seems to work fine for exposing the REST API. We'll add the binary to the image for the tutorial.

@ltalirz why did you add `--region eu --bind-tls true` to the `ngrok`command? Is it ok if we let them run it without these options (it seems to work fine as well).

@ramirezfranciscof could you update the text that helps the participants use the REST API [as you kindly offered before](https://github.com/aiidateam/aiida-tutorials/pull/278#discussion_r531180642)? 🙃 No need to adjust anything regarding how to connect, I'll update this information once we make a branch for the AiiDAlab version, after we complete all the content for the Quantum Mobile version.

**Comment by ramirezfranciscof** [comment]
On it!

**Comment by ramirezfranciscof** [comment]
BTW: @mbercx I think maybe this restapi section could also go together with the query section? So it would be an "Browsing your database" section with 2 subsections: Explore interface and Querybuilder

**Comment by mbercx** [comment]
> On it!

🎉 

> BTW: @mbercx I think maybe this restapi section could also go together with the query section? So it would be an "Browsing your database" section with 2 subsections: Explore interface and Querybuilder

~~That could work! Let's keep it simple though.~~ 😅

EDIT: Wait, but aren't they exploring the REST API _while_ the calculations are running?

**Comment by mbercx** [comment]
> BTW: @mbercx I think maybe this restapi section could also go together with the query section?

@ramirezfranciscof I've added a section on querying to the QE part atm. Feel free to rebase your branch off the one of #282 and reorganise as you see fit. ~~Though, perhaps it would be better if we waited until the branch for the AiiDAlab cluster is set up.~~

➡️ Done! See #284. Maybe first review and merge that PR before working on this.

**Comment by mbercx** [comment]
Resolved by #289
