### ISSUE TITLE
update si graph

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#28]
@odarbelaeze I believe you updated the graph.svg, right?
This graph is used in a different section as well and there it also needs an "input only" version of the figure.
Could you please prepare it and then remove the "batio3" subfolder in sections/include/images/verdi_graph ?

**Comment by odarbelaeze** [comment]
Sounds good, I'll create a PR when I have the SVG version, and PNGs for what I understood.
