### ISSUE TITLE
🐛 Unknown interpreted text role "jupyter-download:nb"

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-tutorials#280]
After updating the `requirements.txt` in #278, the html build raises a warning in the `2020_Intro_Week/sections/data.rst` section on line 216, see [here](https://github.com/aiidateam/aiida-tutorials/pull/278/checks?check_run_id=1460841743#step:6:185) regarding the `jupyter-download:nb` role.

@chrisjsewell Not sure why he doesn't recognise the role. These should a part of `jupyter-sphinx` v0.3.2, no?

**Comment by chrisjsewell** [comment]
yeh it should use `nb-download:filename.ipynb`

**Comment by mbercx** [comment]
Fixed in b89f5dd during branch re-organising.
