### ISSUE TITLE
🔧 Update main page and add acknowledgements

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-tutorials#287]
The current main page still:

- [x] Lists the QM VM
- [x] Double check all versions.
- [x] Doesn't have a link to the AiiDAlab tutorials cluster
- [x] Needs the acknowledgements

**Comment by mbercx** [comment]
@csadorf should I add a Quantum Mobile version to the main page? Which one?

**Comment by csadorf** [comment]
> @csadorf should I add a Quantum Mobile version to the main page? Which one?

Honestly, I don't know. Afaik none of the current releases officially supports AiiDAlab. @chrisjsewell would know more.

**Comment by mbercx** [comment]
Maybe just remove it and add the AiiDAlab version? For the branch we finally merge into master we'll provide the QM, I suppose, unless we decide to recommend users to run tutorials on the AiiDAlab cluster.

**Comment by chrisjsewell** [comment]
> should I add a Quantum Mobile version to the main page? Which one?

I'm releasing version 20.11.0a ~now, which has aiida-core v1.5.0, no aiida lab but does have jupyter lab,
would have been already if I could get stupid openstack to accept my permissions (hopefully, will sort with gio after commonworkflow meeting)

**Comment by chrisjsewell** [comment]
https://quantum-mobile.readthedocs.io/en/latest/releases/both/20.11.0a.html

**Comment by mbercx** [comment]
Resolved in #294
