### ISSUE TITLE
🧪 TEST: no missing connection from setup => start of tutorial

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#292]
The setup section mentions there will be a demonstration on AiiDA lab, but there is no link to a recording or any information on how to follow it.

It is unclear whether this demo is needed to do the tutorial or not.

The hands-on material then starts on the shell, which is not what you see when you enter the account on AiiDA lab, i.e. one should add a sentence there.

The setup section says the server setup will take 'a few minutes' - I think it should not take more than one minute (in my case it didn't).

**Comment by ltalirz** [comment]
Ok, it seems that for the `verdi process list` output in section 1.3 it is assumed that one followed this introduction.
Anything related to this I cannot check

**Comment by mbercx** [comment]
@csadorf do you want to add anything on the AiiDAlab demo? I think since this branch will (probably) not be merged into master, it's ok just to guide people and not provide anything on the steps here.

If not, we can still add a short sentence on moving to the shell.

**Comment by csadorf** [comment]
> The setup section says the server setup will take 'a few minutes' - I think it should not take more than one minute (in my case it didn't).

@ltalirz Unfortunately it can absolutely take a couple of minutes, so I'd rather have folks have a positive surprise than the other way round. Reasons for the delay are not always clear to me, but it is something we should continue to improve.

@mbercx What do you expect here? Some basic script for the AiiDAlab demo?

**Comment by mbercx** [comment]
> @mbercx What do you expect here? Some basic script for the AiiDAlab demo?

I think it's not necessary. This will be explained "live" anyways tomorrow. I'll just add a note on top on the basic section that they have to execute this in a terminal on the AiiDAlab machine.

**Comment by mbercx** [comment]
@csadorf something we should check for this year's tutorial: i.e. make sure this transition is smooth.

More generally, we should make sure that once the tutorial has finished, users coming to the page without any guidance clearly find where to set everything and how to continue.

**Comment by ltalirz** [comment]
There is no longer any mention of an aiidalab presentation on https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro/

Fine to close
