### ISSUE TITLE
uuid tips & tricks very verbose

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#293]
Ok, it's just a drop-down but not sure this is something I want to read the first time I use aiida

![image](https://user-images.githubusercontent.com/1053245/100731624-ea775980-33cb-11eb-9d02-0c8f4d67edcf.png)

You can leave it in here, but please don't merge this into the "basic tutorial" on the aiida web site after the big-map tutorial ends.

**Comment by mbercx** [comment]
Yeah, I agree. 😅  I was merging the Ljubjana "first taste" section (where this came from) with the basic tutorial, so I moved it here, and used a dropdown as a compromise, but I'm happy to remove it, especially since we're strapped for time!

**Comment by mbercx** [comment]
Since we're focussing on the QE part of the tutorial, the tips can stay for reference. See #302
