### ISSUE TITLE
querybuilder example misses exemplary provenance graph

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#299]
you are trying to explain in words what the query does but this is very difficult to understand without knowing what the data looks like.
just add a provenance graph for one material to the notes and it will make it much easier to understand.

**Comment by mbercx** [comment]
I had the same idea, even add some arrows to point to the different `append` steps of the querybuilder. That sounds like something fun to work on this evening. 🙃

**Comment by mbercx** [comment]
In the end we were able to recycle the provenance graph they generated earlier to help explain how the query was built.
