### ISSUE TITLE
Conclussions after first pass of the tutorial

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-tutorials#300]
I just made a first pass going through the tutorial, basically showing how to do everything in a "follow along" kind of way. It took 90 min to do the whole thing, and although I made some pauses I didn't wait 5 min in each as would be more realistic, so maybe I would add 10-20 min to that count for a more accurate estimation.

* Good stopping points are between between the sections (2 and 3, 3 and 4) and between 2.3 and 2.4 and 4.1 and 4.2 (restapi explore browse and querybuilder).
* Since we are looking to reduce a bit section 2, perhaps it is a bit redundant to both `run` AND `submit` the calcjob? Maybe we can directly submit it (in my pass I think I spend some unnecessary time here, even if we leave it, if I did it again I would probably just leave them to do this part or copy paste and just make a paraphrasing comment of "its the same thing")
* I think we need to just put `wget path/to/script.py` for all the demo scripts we have there; it makes no sense to spend time getting, copying, whatever the file if they can just run one command. Also, the wget for the new silicon structure just says `wget <LINK>`: was this intentional? I would just copy paste the link here so they can just run the command.

**Comment by ramirezfranciscof** [comment]
@mbercx feedback?

**Comment by mbercx** [comment]
Good points, @ramirezfranciscof! I agree that doing both running and submitting is perhaps unnecessary, at least for the purpose of tomorrow's event. Also, now that the RTD version is set, we can indeed just update the `wget` snippets to the correct links and not worry about the right clicking etc (this wasn't possible before 😅 ).

**Comment by mbercx** [comment]
Will work on fixing `wget` snippets to this idea in a more general PR with minor fixes also for the issues @ltalirz raised.

**Comment by ramirezfranciscof** [comment]
Closing because it is no longer relevant due to the changes in general structure.
