### ISSUE TITLE
✨ NEW: Video Request: Installing AiiDA

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-tutorials#328]
From last virtual tutorial (July 2020):

> Someone requested to record Chris’ installing instructions. I wasn’t able to allow it as the meeting was running. But I think it would be good if Chris made a video on this process, same as he had done for the setup of the VM’s.

**Comment by chrisjsewell** [comment]
yep sounds good 👍

**Comment by chrisjsewell** [comment]
done
