### ISSUE TITLE
👌 IMPROVE: Module: Data - Organising your data

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-tutorials#342]
The module on "Organising your data" discusses:

* How to create, show and manipulate groups.
* How to add/remove nodes to/from groups.
* How to organise groups in hierarchies.

The content is already in good shape, so the main point of this issue is to go over the material and see if it can still be improved somehow. Are the explanations clear? Would you add/remove something? Does the material adhere to the [principles of a tutorial](https://documentation.divio.com/tutorials/)? That sort of thing.

Although testing the tutorial content is of course fine, note that we'll do a full round of testing in the week of the 21st.

**Comment by mbercx** [comment]
Also pinging @chrisjsewell if he has any comments, since I think he originally wrote this content.

**Comment by ltalirz** [comment]
Closed in #364
