### ISSUE TITLE
👌 IMPROVE: Module: Data - Querying

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-tutorials#343]
The module on quering teached the participant how to:

* Build a simple query to look for certain types of nodes.
* How to _project_ certain information in a query.
* Using filters to restrict the nodes in our query.
* Defining relationships between query clauses.
* Generate a provenance graph with the Python API.

The tutorial content is already in good shape, so the explanations just have to be revised for clarity, and perhaps something still needs to be removed/added. It would also be good to check if the material language is consistent with that of the ["How to find and query for data" section](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/query.html).

**Comment by mbercx** [comment]
Also pinging @chrisjsewell if he has any comments, since I think he originally wrote this content.

**Comment by ltalirz** [comment]
Closed in #365
