### ISSUE TITLE
👌 IMPROVE: Module: Fundamentals - AiiDA basics

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-tutorials#344]
The AiiDA basics module explains:

* The concept of provenance.
* How to create data nodes and store them.
* How to run a Python function and store the provenance with `calcfunction`s.
* How to set up a code and run a `CalcJob`.
* The difference between _running_ and _submitting_.
* Running a worklow

These are all explained using basic addition and multiplication. As the original author of this section, I think the content is of course amazing, but I suppose it could still be perfected a little bit more. Some things to consider:

* Adding entry points (also see https://github.com/aiidateam/aiida-core/issues/4544 and #283)
* (Will add more if I think of stuff)

**Comment by mbercx** [comment]
Quick note, since ~this section is my baby~ I wrote this section originally, I would like to have the chance to review the PR with changes before it is merged. 😁

**Comment by ltalirz** [comment]
Closed in #376
