### ISSUE TITLE
👌 IMPROVE: "Running calculations - Basics" module

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-tutorials#355]
Continuing from the AiiDA Basics in the "Fundamentals" section, the first thing we want the participants to do is to run their own Quantum ESPRESSO calculation using AiiDA, so they can understand more about:

* How to import a structure
* How to set up a code
* How to install pseudopotentials
* How to set up inputs for a calculation
* How to analyse outputs of a calculation

This section will be largely based on the one used for the BIGMAP/ABC/QEschool tutorials, but could do with a quick revision.

**Comment by ltalirz** [comment]
Closed in #366
