### ISSUE TITLE
👌 IMPROVE: Tutorial section naming

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-tutorials#373]
Currently the sections are named:

- "Fundamentals"
- "Running processes"
- "Data"
- "Workflows"
- "Plugins"

In principle I think it would be better to be more explicit about the difference with "Workchains" and "Running processes" ("aren't workchains a kind of process?") and rename that to "Writting workchains" ("ahh so first you learn to run and then you make your own"). Since we are changing that and I like symmetry, I thought we could adapt the rest as well:

- "Fundamentals" (or "Getting started")
- "Running processes"
- "Managing data"
- "Writing workflows"
- "Creating plugins"

Ideas? Thought? Pizza? 🍕 ?

**Comment by mbercx** [comment]
Agreed! Just one correction: The 4th section (or unit/chapter/whateverwecallit) is called "Workflows", and as such, I'd call the verb-noun version: "Writing workflows". Other than that, I think your suggestion is good.

"Fundamentals" (although it was my suggestion) did always sound a bit off to me. Maybe "Getting Started" is better? It contains Setup and AiiDA Basics for now.

**Comment by ramirezfranciscof** [comment]
> Agreed! Just one correction: The 4th section (or unit/chapter/whateverwecallit) is called "Workflows", and as such, I'd call the verb-noun version: "Writing workflows". Other than that, I think your suggestion is good.

Ah yeah, sorry that was just a typo, I corrected it now.

> "Fundamentals" (although it was my suggestion) did always sound a bit off to me. Maybe "Getting Started" is better? It contains Setup and AiiDA Basics for now.

Getting started is a decent "style conforming" option.

**Comment by mbercx** [comment]
Closed by #380
