### ISSUE TITLE
Error 305: Cannot run Quantum Espresso

### ISSUE THREAD

**Issue by m-a-saleh** [aiidateam/aiida-tutorials#399]
I have installed `aiida-quantumespresso` plugin and `SSSP pseudo library`.

Added a computer:
```
label: "localhost"
hostname: "localhost"
description: "This is my local pc"
transport: local
scheduler: "slurm"
work_dir: "/home/saleh/.aiida_run"
mpirun_command: "mpirun -np {tot_num_mpiprocs}"
mpiprocs_per_machine: "2"
prepend_text: |
   source /opt/intel/oneapi/setvars.sh
```
Added qe-pw code:
```
label: "qe-pw-6.7"
description: "quantum_espresso v6.7"
input_plugin: "quantumespresso.pw"
on_computer: true
remote_abs_path: "/home/saleh/qe-6.7/bin/pw.x"
computer: "localhost"
prepend_text: |
   ulimit -s unlimited
append_text: " "
```
Run a test PwCalculation
`aiida-quantumespresso calculation launch pw -X qe-pw-6.7 -F SSSP/1.1/PBE/efficiency`

Got the following error:
```
07/27/2021 08:58:57 AM <47989> aiida.parser.PwParser: [ERROR] Both the stdout and XML output files could not be read or parsed.
07/27/2021 08:58:57 AM <47989> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [WARNING] output parser returned exit code<305>: Both the stdout and XML output files could not be read or parsed.
PwCalculation<111> terminated with state: finished [305] `Both the stdout and XML output files could not be read or parsed.
```

To get an idea what the exit code `305` is, I ran:
`verdi plugin list aiida.calculations quantumespresso.pw`

The result is:
```
Exit codes:
                        305:  Both the stdout and xml output files could not be read or parsed.
```
To see the output file:
`verdi calcjob outputcat 111`

I got:
```
Critical: Could not open output path "aiida.out". Exception: [Errno 2] No such file or directory: '/home/saleh/.aiida/repository/quicksetup/repository/node/06/36/a94a-72e9-4a43-9469-92e46cc62edb/path/aiida.out'
```

**Comment by mbercx** [comment]
Hi @m-a-saleh! 👋 Could you check what files are present, with:

`verdi calcjob outputls 111` (Edited, sorry! Was a little quick)

I don't use the CLI very often, so it's possible a bug was introduced at some point that missed the testing. 😅

**Comment by m-a-saleh** [comment]
There is no output file

running `verdi calcjob outputcat 111` gives
```
Critical: Could not open output path "aiida.out". Exception: [Errno 2] No such file or directory: '/home/saleh/.aiida/repository/quicksetup/repository/node/06/36/a94a-72e9-4a43-9469-92e46cc62edb/path/aiida.out'
```

**Comment by mbercx** [comment]
Whoops! Seems I made some copy 🍝 . I fixed the command to the one that shows which output files are there:

```
verdi calcjob outputls 111
```

**Comment by mbercx** [comment]
Whoops! Seems I made some copy 🍝 . I fixed the command to the one that shows which output files are there:

```
verdi calcjob outputls 111
```

**Comment by m-a-saleh** [comment]
```
_scheduler-stderr.txt
_scheduler-stdout.txt
```

**Comment by mbercx** [comment]
As you can see, the `aiida.out` file, where the `stdout` of Quantum ESPRESSO is written, is not present. So something else went wrong in the submission of the job. You can have a look at the scheduler `stderr` using:

```
verdi calcjob outputcat 111 _scheduler-stderr.txt
```

That might give more of an idea of what went wrong. If not, you can also check the corresponding `stdout` file.

**Comment by m-a-saleh** [comment]
After removing 
```
prepend_text: |
   source /opt/intel/oneapi/setvars.sh
``` 
from the computer setup, the calculation now works (calculations finished with return code 0 and there is a correct output file).

**Comment by mbercx** [comment]
Good to hear! I'll close this then 👍
