### ISSUE TITLE
Migrate to GitHub Pages

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-tutorials#4]
Idea: migrate to MarkDown so the documentation can be viewed online (ideally with the GitHub pages automatic feature)

Requirements:
- be able to create a PDF version of the documentation (compilable with LaTeX)

@ltalirz and me are going to work on this (also reusing some of the work I'm doing to do the same for the Wannier90 code)

**Comment by odarbelaeze** [comment]
The HTML output of the `make html` command, can be dropped in github pages automatically. Together with a `.nojekyll` file to prevent github from trying to process the contents. The tricky part is to have branches working _alla_ read the docs.

**Comment by odarbelaeze** [comment]
@giovannipizzi @ltalirz I would like to get a little context about this task. I'm thinking you can use the `html` output of sphinx and serve that from github pages, then if `sphinx` is working the markdown files don't need any updates.

**Comment by ltalirz** [comment]
This was written when there was only a latex source file of the tutorial. No need to worry, I'll close it for now to avoid further confusion
