### ISSUE TITLE
Update link to peroskite archive once given permanent URL

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-tutorials#40]
Pull request #35 added a link to the newly created export archive needed for the advanced querybuilder tutorial. It currently points to a temporary URL but once the archive has been proven to work, it should be made available at a permanent URL and the link should be adapted

**Comment by ltalirz** [comment]
+ put the file on the VM as a fallback

**Comment by ltalirz** [comment]
The export file is now available online

https://object.cscs.ch/v1/AUTH_b1d80408b3d340db9f03d373bbde5c1e/marvel-vms/tutorials/aiida_tutorial_2019_05_perovskites_v0.1.aiida

**Comment by sphuber** [comment]
Is this the first version I put on the team drive, or the second one, with the added process attributes and fixed pseudo link labels?
