### ISSUE TITLE
Issue on page /sections/getting_started/basics.html

### ISSUE THREAD

**Issue by Clarkszw** [aiidateam/aiida-tutorials#415]
Hi,

I am setting up the localhost computer by

`verdi computer setup -L localhost -H localhost -T local -S direct -w `echo $HOME/aiida_run` --mpiprocs-per-machine 1 -n`

But it shows:
`Error: Invalid value for '-T' / '--transport': entry point 'local' is not valid for any of the allowed entry point groups: aiida.transports`

Could you help me with this? I am on my Mac OS X Catalina 10.15.7

Thanks in advance:)

**Comment by mbercx** [comment]
Hi @Clarkszw! Unfortunately, the tutorial documentation hasn't been updated yet for AiiDA core v2.0 (we'll be working on this in preparation of the upcoming tutorial in October). All of the plugin entry points have been changed by prepending `core.`, in order to make their format consistent with those of the plugin packages, see:

https://github.com/aiidateam/aiida-core/wiki/AiiDA-2.0-plugin-migration-guide#entry-points

So you have to add this `core.` prefix to the `core.local` transport and `core.direct` scheduler:

```console
verdi computer setup -L localhost -H localhost -T core.local -S core.direct -w echo $HOME/aiida_run --mpiprocs-per-machine 1 -n
```

Hope that helps!

**Comment by Clarkszw** [comment]
Hi @mbercx, thanks for the instruction. This makes sense!
now I got this Error..
`Error: Got unexpected extra argument (/Users/imac/aiida_run)`
..What can I do to fix it?

**Comment by Clarkszw** [comment]
Hi @mbercx, 
I have tried to remove echo in -w option. It worked, not sure if it is ok?
what is the difference between
```
-w echo $HOME/aiida_run
```
```
-w $HOME/aiida_run
```
```
-w `echo $HOME/aiida_run` 
```
( in the tutorial there is backtick mark..)

Thanks in advance:)

**Comment by mbercx** [comment]
Oh, right, I was also sloppy in my example regarding the working directory option `-w`.  Using the backticks, the bash command between the backticks will be executed, so you'll get the absolute path to `$HOME/aiida_run`, which is what you want. If you've run without the `-w` option, I'm assuming the working directory (where AiiDA will run the calculations) won't be set (you can check this with `verdi computer show localhost`). In that case, best to delete this computer and run the setup command again with the backticks in place properly.

**Comment by Clarkszw** [comment]
Hi @mbercx,
I think it looks fine now. Thanks again for the help:)
```
Label                        localhost
PK                           1
UUID                         576f1247-746a-4f6c-b1f6-7142308646f2
Description
Hostname                     localhost
Transport type               core.local
Scheduler type               core.direct
Work directory               /Users/imac/aiida_run
Shebang                      #!/bin/bash
Mpirun command               mpirun -np {tot_num_mpiprocs}
Default #procs/machine       1
Default memory (kB)/machine
Prepend text
Append text
```
