### ISSUE TITLE
add verdi quicksetup

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#43]
The concept of profiles in order to organize your work is an important part of learning how to use AiiDA.

To do:
 - [ ] Decide: do we do this at the beginning of the tutorial or somwhere in between?
 - [ ] Note: after setting up the new profile, they will need to set up their codes
    * We can provide `computer.yaml`, `code.yaml` files for this and use the new `--config` option

**Comment by ltalirz** [comment]
Decision:
 * start with quicksetup at the beginning
 * then set up computers + codes when they are needed

**Comment by sphuber** [comment]
What is the default profile configured on the VM? I.e. what is the output of `verdi profile list` and `verdi profile show`?

**Comment by ltalirz** [comment]
for testing, feel free to take the "empty" VM from the tutorial doc

**Comment by sphuber** [comment]
I noticed that the "default" profile on the VM is called "default" :)  This makes what I am trying to explain a bit confusing. Would it be possible to change this to something else? During the `verdi quicksetup` section I also have them use `verdi profile list` and explain the concept of the default profile and the `-p/--profile` options for `verdi`

**Comment by ltalirz** [comment]
> Would it be possible to change this to something else? 

Certainly, any good ideas? The name should make sense both for the tutorial VM and for quantum mobile.

**Comment by sphuber** [comment]
To be honest, I have no idea :sweat_smile: that's why I didn't propose any.
Maybe:
* `aiida`
* `auto`
* `max` (would make sense for QM (but not really VM) since I think the user is called Max Scientist there correct?)

**Comment by ltalirz** [comment]
I vote for `generic`

**Comment by ltalirz** [comment]
adddressed in #85
