### ISSUE TITLE
Issue on page /sections/getting_started/basics.html

### ISSUE THREAD

**Issue by superstar54** [aiidateam/aiida-tutorials#433]
I start to go through the tutorial 2022 on Azure https://aiida-tutorial-2022.aiidalab.io/

I got this error:
```
jovyan@jupyter-superstar54:~$ verdi status -h
Usage: verdi status [OPTIONS]
Try 'verdi status --help' for help.

Error: No such option: -h
```
It seems that the latest AiiDA does not support the option `-h`.

**Comment by mbercx** [comment]
Thanks @superstar54! I think this issue was fixed in #432? See

https://aiida-tutorials.readthedocs.io/en/tutorial-2022-intro/sections/getting_started/basics.html

So I'll close this issue for now, but feel free to reopen in case I missed anything.
