### ISSUE TITLE
Import aiida database in "Verdi command line"

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-tutorials#48]
Otherwise the aiida cmdline interface can't be properly tested

**Comment by yakutovicha** [comment]
After discussion we agreed that better place would be "Verdi command line"

**Comment by sphuber** [comment]
> After discussion we agreed that better place would be "Verdi command line"

I am going through that section now. What did you guys agree on? Should I start the section with an import command?

**Comment by yakutovicha** [comment]
Yes, starting the section with import would be best.

We also realized that the link you provide in https://github.com/aiidateam/aiida-tutorials/pull/35 can't be directly used in `verdi import url`. We may want to use dropbox link (or something else) instead

**Comment by sphuber** [comment]
Yes, that's why I opened #40 . Once we have finalized the archive and fully tested it, we should upload it somewhere permanent. On MaterialsCloud, Zenodo, anything that gives a semi-permanent and public URL.

**Comment by ltalirz** [comment]
fixed in #73
