### ISSUE TITLE
Section 5 on QueryBuilder contains an error

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-tutorials#5]
The text explains where to find the `tutorial.ipynb` file, but the path is incorrect on the Quantum Mobile VM. In addition it mentions that the `solution.ipynb` is there, but `Makefile` was not run, so the file does not exist on the VM.

**Comment by ltalirz** [comment]
This was addressed in the 2019-marvel-psik event (where the jupyter notebook is simply downloaded from the web)
