### ISSUE TITLE
Make sure there's an x server running in the virtual machine

### ISSUE THREAD

**Issue by odarbelaeze** [aiidateam/aiida-tutorials#56]
I the text of the tutorial, it says:

> you will create a pdf file <pk>.pdf. You can open this file on the Amazon machine by using evince or, if you feel that the ssh connection is too slow, copy it via scp to your local machine. To do so, if you are using Linux/Mac OS X, you can type in your local machine:

However, in my test machine I get this error:

```bash
(aiida) max@ip-172-31-11-37:~$ evince 833.pdf
Unable to init server: Could not connect: Connection refused
Cannot parse arguments: Cannot open display: 
```

I'm connecting to the machine with the following configuration:

```bash
$ ssh -i ~/Downloads/aiida-tutorial-max.pem -L 8888:localhost:8888 -X -C max@34.244.118.139
```

Another offender is the `verdi data structure show` command [here](https://aiida-tutorials.readthedocs.io/en/tutorial_2019_05/pages/2019_MARVEL_Psik_MaX/sections/verdi_cmdline.html#structuredata), this is the specific error:

```bash
(aiida) max@ip-172-31-11-37:~$ verdi data structure show --format ase 3a4b1270
(aiida) max@ip-172-31-11-37:~$ usage: ase [-h] [--version] [-T]
           {help,info,test,gui,db,run,band-structure,build,eos,ulm,find,nomad-upload,nomad-get,convert,reciprocal,completion}
           ...
ase: error: TclError: no display name and no $DISPLAY environment variable
To get a full traceback, use: ase -T gui ...
^C
```

**Comment by ltalirz** [comment]
fixed in #73
