### ISSUE TITLE
provenance browser does now show file content

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-tutorials#6]
When clicking on the "eye" symbol, the provenance browser e.g. [here](http://34.244.178.26:5001/explore/sssp/details/5b3ae333-1e30-4296-8118-363649acace3?nodeType=CALCULATION) does not show file contents in the browser.

Downloading files works, however.
<img width="429" alt="screenshot 2019-01-15 at 09 21 30" src="https://user-images.githubusercontent.com/1053245/51167521-14423880-18a7-11e9-9cbb-c61179d4a872.png">

**Comment by ltalirz** [comment]
@waychal do you have an idea what could be causing this (i.e. download works but clicking on eye symbol doesn't)?

**Comment by ltalirz** [comment]
To my knowledge, this issue has not resurfaced during the May 2019 tutorial.
I think it can be considered fixed - thanks to @waychal !

**Comment by waychal** [comment]
@ltalirz yes, this one is fixed and we are not using highlight.js library anymore there.
