### ISSUE TITLE
Computer Setup and Configuration

### ISSUE THREAD

**Issue by nitishg91** [aiidateam/aiida-tutorials#7]
I get the following message then trying to download the ssh key: 

$ wget  https://www.dropbox.com/s/.../aiida_tutorial_aiidaaccount?dl=1 -O /home/max/.ssh/aws.pem

/home/max/.ssh/aws.pem: No such file or directory

So, I presume this is because there is no .ssh directory in /home/max, and it has to first be created.

I did this, and then I get the following error:

--2019-01-15 14:30:09--  https://www.dropbox.com/s/.../aiida_tutorial_aiidaaccount?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.65.1, 2620:100:6021:1::a27d:4101
Connecting to www.dropbox.com (www.dropbox.com)|162.125.65.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/.../aiida_tutorial_aiidaaccount [following]
--2019-01-15 14:30:10--  https://www.dropbox.com/s/dl/.../aiida_tutorial_aiidaaccount
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2019-01-15 14:30:10 ERROR 404: Not Found.

**Comment by ltalirz** [comment]
hi @nitishg91 , you are proceeding faster than us ;-)
As mentioned in the email, only tasks 1-4 are ready so far; we'll let you know once more has been updated.

**Comment by ltalirz** [comment]
Are tasks 1-4 working for you?
