### ISSUE TITLE
Appendix 2: `dict(restart_builder.parameters.dict)` is not working

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-tutorials#74]
```
dict(restart_builder.parameters.dict)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-2d4fe41e5ba5> in <module>()
----> 1 dict(restart_builder.parameters.dict)

ValueError: dictionary update sequence element #0 has length 9; 2 is required
```

`dict` should be probably replaced by get_dict()

Also, the whole line looks strange:
```
parameters = dict(restart_builder.parameters.dict)['ELECTRONS']['electron_maxstep'] = 80
```

shouldn't it be replaced by:
```
parameters = dict(restart_builder.parameters.get_dict())
parameters['ELECTRONS']['electron_maxstep'] = 80
```
?

**Comment by yakutovicha** [comment]
same for:
```
parameters = dict(restart_builder.parameters.dict)['CONTROL']['restart_mode'] = 'restart'
```

**Comment by ltalirz** [comment]
Actually, [there is a .dict property](https://github.com/aiidateam/aiida_core/blob/c95937965212454a8d1bce73799fc13ef7691184/aiida/orm/nodes/data/dict.py#L90) (but no related setter).

@sphuber Can you please advise on the recommended way to update the `restart_builder`?

**Comment by sphuber** [comment]
This is not really a problem of the builder as it is of the `Dict` class. I wanted to keep it as short as possible, but clearly made a mistake. The following should definitely work, but might be a bit verbose:
```
parameters = restart_builder.parameters.get_dict()
parameters['CONTROL']['restart_mode'] = 'restart'
restart_builder = Dict(dict=parameters)
```
I have been thinking of allowing attribute setters on stored `Dict` nodes, which will simply return an unstored copy with the changed attribute, but maybe this "magic" may confuse users who are not yet well versed in stored and unstored nodes.

**Comment by ltalirz** [comment]
> I have been thinking of allowing attribute setters on stored Dict nodes

What about allowing attribute setters on *unstored* Dict nodes?

> but maybe this "magic" may confuse users who are not yet well versed in stored and unstored nodes.

I agree. If I try to set an attribute on a stored node, I would expect it to fail.
