### ISSUE TITLE
Appendix 4.1: pressure_convergence.py does not work

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-tutorials#77]
Moreover, text says that it should be in `tutorial_scripts/pressure_convergence.py`, while in reality it is in `/home/max/examples/aiida-demos/tutorial/scripts`

**Comment by ltalirz** [comment]
also this script is now in the tutorials

**Comment by sphuber** [comment]
Should we remove the `aiida-demos` repository from the VM? Or at least update it so that it no longer contains those old outdated scripts. If users find those by accident, they won't work

**Comment by sphuber** [comment]
And at @yakutovicha are you sure you have the version from `aiida-tutorials`? Where is this uploaded on the VM @ltalirz ? Or it isn't and every script should be made available through download links

**Comment by ltalirz** [comment]
> Or at least update it so that it no longer contains those old outdated scripts.

Yes, this will be the case.

**Comment by yakutovicha** [comment]
Just tested it using:
```
run(PressureConvergence, code=load_code('qe-6.3-pw@localhost'), structure=load_node('3a4b1270'), pseudo_family=Str('SSSP'), volume_tolerance=Float(1e-3))
```
and it works!
