### ISSUE TITLE
Section 2.4.2: Make the stdout redirection a little more obvious in this section

### ISSUE THREAD

**Issue by odarbelaeze** [aiidateam/aiida-tutorials#79]
`sections/verdi_cmdline.html#structuredata`

In this section, I feel like the flow of the tutorial is to delete what's in `<>` it happened to me twice that I remove the `>` stdout redirection operator, I read this

```bash
$ verdi data structure export --format xsf <IDENTIFIER> > <IDENTIFIER>.xsf
```

we might want to improve here providing an actual uuid, maybe we could include a comment and a command like:

```bash
# verdi data structure export --format xsf <IDENTIFIER> > <IDENTIFIER>.xsf
verdi data structure export --format xsf 254e5a86 > 254e5a86.xsf
```

The uuids would only need to be replaced if we ever change our export.

**Comment by ltalirz** [comment]
closed in #93
