### ISSUE TITLE
Add extra acknowledgements in README.md

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-tutorials#89]
Acknowledgements to be added:
- [ ] swissuniversities
- [ ] Psi-k network
- [ ] EPFL
- [ ] intersect

**Comment by ltalirz** [comment]
@CasperWA good point, please go ahead with this

**Comment by ltalirz** [comment]
you might even want to include them at the bottom of the page here:
https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_MARVEL_Psik_MaX/index.html

**Comment by ltalirz** [comment]
I've just added the sponsor logos on the respective tutorial page.
I think it's not really necessary to add them to the README as well (people will go to the web site anyhow) but feel free to do so - closing via PR #117 .
